name: Python Bandit Scan
 on: [pull_request]
 jobs: 
   security_scan:
     name: Security Scan
     runs-on: self-hosted
     steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-python@v4
       with:
         python-version: '3.10'
     - name: Run Bandit Check
       uses: jpetrucciani/bandit-check@master
